"""Session name generation and validation."""

from __future__ import annotations

import random
import re
from typing import Final

# ~100 adjectives for name generation
ADJECTIVES: Final[tuple[str, ...]] = (
    "happy",
    "sleepy",
    "clever",
    "brave",
    "calm",
    "eager",
    "fierce",
    "gentle",
    "humble",
    "jolly",
    "keen",
    "lively",
    "merry",
    "noble",
    "proud",
    "quick",
    "rapid",
    "sharp",
    "swift",
    "tidy",
    "upbeat",
    "vivid",
    "witty",
    "zesty",
    "bold",
    "cool",
    "dark",
    "epic",
    "fair",
    "grand",
    "huge",
    "ideal",
    "just",
    "kind",
    "light",
    "main",
    "neat",
    "open",
    "pure",
    "rare",
    "safe",
    "true",
    "vast",
    "warm",
    "young",
    "azure",
    "bright",
    "crisp",
    "deep",
    "fine",
    "glad",
    "high",
    "iron",
    "jet",
    "keen",
    "long",
    "mad",
    "new",
    "odd",
    "pink",
    "red",
    "silver",
    "tall",
    "urban",
    "violet",
    "white",
    "yellow",
    "amber",
    "blue",
    "cyan",
    "dawn",
    "elm",
    "frost",
    "gold",
    "hazel",
    "indigo",
    "jade",
    "khaki",
    "lime",
    "mint",
    "navy",
    "olive",
    "pearl",
    "quartz",
    "rose",
    "sage",
    "teal",
    "umber",
    "violet",
    "wheat",
    "xanthic",
    "yew",
    "zinc",
    "aqua",
    "bronze",
    "copper",
    "diamond",
    "emerald",
    "flame",
    "garnet",
    "hematite",
    "ivory",
    "jasper",
    "krypton",
    "lead",
    "mercury",
    "nickel",
    "opal",
    "platinum",
    "quicksilver",
)

# ~100 nouns for name generation
NOUNS: Final[tuple[str, ...]] = (
    "fox",
    "bear",
    "otter",
    "panda",
    "tiger",
    "eagle",
    "falcon",
    "gecko",
    "hawk",
    "ibis",
    "jaguar",
    "koala",
    "lemur",
    "meerkat",
    "newt",
    "ocelot",
    "penguin",
    "quail",
    "raven",
    "shark",
    "tiger",
    "urchin",
    "viper",
    "whale",
    "xerus",
    "yak",
    "zebra",
    "ant",
    "bee",
    "cat",
    "dog",
    "elk",
    "frog",
    "goat",
    "horse",
    "iguana",
    "jackal",
    "kangaroo",
    "lion",
    "mouse",
    "nightingale",
    "owl",
    "parrot",
    "rabbit",
    "snake",
    "toad",
    "unicorn",
    "vulture",
    "wolf",
    "ox",
    "ape",
    "bat",
    "crane",
    "deer",
    "eel",
    "flamingo",
    "giraffe",
    "hare",
    "impala",
    "jellyfish",
    "kingfisher",
    "lynx",
    "mole",
    "narwhal",
    "octopus",
    "panther",
    "quokka",
    "rhino",
    "seal",
    "turkey",
    "vampire",
    "wombat",
    "xenops",
    "yabby",
    "zorilla",
    "armadillo",
    "buffalo",
    "cheetah",
    "dolphin",
    "emu",
    "ferret",
    "gazelle",
    "hedgehog",
    "insect",
    "jay",
    "kitten",
    "leopard",
    "mongoose",
    "narwhal",
    "oyster",
    "peacock",
    "quail",
    "reindeer",
    "sloth",
    "turtle",
    "urchin",
    "velvet",
    "walrus",
    "xerus",
    "yaffle",
    "zebra",
    "albatross",
    "butterfly",
    "caterpillar",
)

# Name format: starts with letter, contains lowercase letters/numbers/hyphens, ends with alphanumeric
NAME_PATTERN: Final[re.Pattern[str]] = re.compile(r"^[a-z][a-z0-9-]*[a-z0-9]$")


def is_valid_name(name: str) -> bool:
    """Check if name matches the required format.

    Format: [a-z][a-z0-9-]*[a-z0-9]
    - Starts with lowercase letter
    - Contains only lowercase letters, numbers, and hyphens
    - Ends with letter or number (no trailing hyphen)
    - Minimum 2 characters
    """
    if len(name) < 2:
        return False
    return bool(NAME_PATTERN.match(name))


def generate_name() -> str:
    """Generate a random Docker-style name: adjective-noun-number.

    Example: "happy-fox-42"
    """
    adjective = random.choice(ADJECTIVES)
    noun = random.choice(NOUNS)
    number = random.randint(0, 99)
    return f"{adjective}-{noun}-{number}"


__all__ = ["ADJECTIVES", "NOUNS", "NAME_PATTERN", "is_valid_name", "generate_name"]
